import 'package:flutter/material.dart';

const kUnpickedCoinColor = Colors.transparent; //0xFF434344 - dull black
const kPickedCoinColor = Color(0xff02d2f8); //0xFF0A84FF
// const kPickedCoinColor = Colors.black; //0xFF0A84FF

const kAppBarText = TextStyle(
  fontSize: 25.0,
  letterSpacing: 2,
  wordSpacing: 3,
);

const kSelectionButton = TextStyle(
  fontSize: 30.0,
);

// var kCoinColor = {
//   '01': kUnpickedCoinColor,
//   '02': kUnpickedCoinColor,
//   '03': kUnpickedCoinColor,
//   '04': kUnpickedCoinColor,
//   '05': kUnpickedCoinColor,
//   '06': kUnpickedCoinColor,
//   '07': kUnpickedCoinColor,
//   '08': kUnpickedCoinColor,
//   '09': kUnpickedCoinColor,
//   '10': kUnpickedCoinColor,
//   '11': kUnpickedCoinColor,
//   '12': kUnpickedCoinColor,
//   '13': kUnpickedCoinColor,
//   '14': kUnpickedCoinColor,
//   '15': kUnpickedCoinColor,
//   '16': kUnpickedCoinColor,
//   '17': kUnpickedCoinColor,
//   '18': kUnpickedCoinColor,
//   '19': kUnpickedCoinColor,
//   '20': kUnpickedCoinColor,
//   '21': kUnpickedCoinColor,
//   '22': kUnpickedCoinColor,
//   '23': kUnpickedCoinColor,
//   '24': kUnpickedCoinColor,
//   '25': kUnpickedCoinColor,
//   '26': kUnpickedCoinColor,
//   '27': kUnpickedCoinColor,
//   '28': kUnpickedCoinColor,
//   '29': kUnpickedCoinColor,
//   '30': kUnpickedCoinColor,
//   '31': kUnpickedCoinColor,
//   '32': kUnpickedCoinColor,
//   '33': kUnpickedCoinColor,
//   '34': kUnpickedCoinColor,
//   '35': kUnpickedCoinColor,
//   '36': kUnpickedCoinColor,
//   '37': kUnpickedCoinColor,
//   '38': kUnpickedCoinColor,
//   '39': kUnpickedCoinColor,
//   '40': kUnpickedCoinColor,
//   '41': kUnpickedCoinColor,
//   '42': kUnpickedCoinColor,
//   '43': kUnpickedCoinColor,
//   '44': kUnpickedCoinColor,
//   '45': kUnpickedCoinColor,
//   '46': kUnpickedCoinColor,
//   '47': kUnpickedCoinColor,
//   '48': kUnpickedCoinColor,
//   '49': kUnpickedCoinColor,
//   '50': kUnpickedCoinColor,
//   '51': kUnpickedCoinColor,
//   '52': kUnpickedCoinColor,
//   '53': kUnpickedCoinColor,
//   '54': kUnpickedCoinColor,
//   '55': kUnpickedCoinColor,
//   '56': kUnpickedCoinColor,
//   '57': kUnpickedCoinColor,
//   '58': kUnpickedCoinColor,
//   '59': kUnpickedCoinColor,
//   '60': kUnpickedCoinColor,
//   '61': kUnpickedCoinColor,
//   '62': kUnpickedCoinColor,
//   '63': kUnpickedCoinColor,
//   '64': kUnpickedCoinColor,
//   '65': kUnpickedCoinColor,
//   '66': kUnpickedCoinColor,
//   '67': kUnpickedCoinColor,
//   '68': kUnpickedCoinColor,
//   '69': kUnpickedCoinColor,
//   '70': kUnpickedCoinColor,
//   '71': kUnpickedCoinColor,
//   '72': kUnpickedCoinColor,
//   '73': kUnpickedCoinColor,
//   '74': kUnpickedCoinColor,
//   '75': kUnpickedCoinColor,
//   '76': kUnpickedCoinColor,
//   '77': kUnpickedCoinColor,
//   '78': kUnpickedCoinColor,
//   '79': kUnpickedCoinColor,
//   '80': kUnpickedCoinColor,
//   '81': kUnpickedCoinColor,
//   '82': kUnpickedCoinColor,
//   '83': kUnpickedCoinColor,
//   '84': kUnpickedCoinColor,
//   '85': kUnpickedCoinColor,
//   '86': kUnpickedCoinColor,
//   '87': kUnpickedCoinColor,
//   '88': kUnpickedCoinColor,
//   '89': kUnpickedCoinColor,
//   '90': kUnpickedCoinColor,
// };
